CREATE TABLE CLIENTE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR(11)
);

CREATE TABLE PRODUTO (
    ID INTEGER PRIMARY KEY auto_increment,
    NOME VARCHAR(40),
    PRECO NUMERIC(20,2)
);
CREATE TABLE PEDIDO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INTEGER REFERENCES CLIENTE(ID),
    DATA_PEDIDO TIMESTAMP,
    TOTAL NUMERIC(20,2),
    NUMERO_CONTROLE INTEGER
);
CREATE TABLE ITEM_PEDIDO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUTO INTEGER REFERENCES PRODUTO(ID),
    ID_PEDIDO INTEGER REFERENCES PEDIDO(ID),
    QUANTIDADE INTEGER
);